# Generated by Django 5.2.2 on 2025-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ve_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('projects_count', models.PositiveIntegerField()),
                ('experience_level', models.CharField(max_length=100)),
                ('performance_score', models.PositiveIntegerField()),
                ('rotation_rank', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned')], default='available', max_length=20)),
                ('current_project', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
