# Generated by Django 5.2.2 on 2025-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0002_alter_teammember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='experience_level',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Moderator', 'Moderator'), ('Regular', 'Regular'), ('Backchecker', 'Backchecker'), ('Mobilizer', 'Mobilizer')], max_length=50),
        ),
    ]
