# Generated by Django 5.2.2 on 2025-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0004_alter_teammember_experience_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='current_project',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='projects_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='datacollectors_app.project'),
        ),
    ]
