# Generated by Django 5.2.2 on 2025-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0006_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('data_collector', 'Data Collector')], max_length=20),
        ),
    ]
