# Generated by Django 5.2.2 on 2025-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0007_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='experience_level',
            field=models.CharField(choices=[('Foa', 'FOA'), ('Supervisor', 'Supervisor'), ('Backchecker', 'Backchecker'), ('Regular', 'Regular'), ('New Enumerator', 'New Enumerator')], max_length=50),
        ),
    ]
