# Generated by Django 4.2.23 on 2025-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0009_alter_project_options_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
