# Generated by Django 4.2.23 on 2025-06-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0011_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollectors_app.project')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollectors_app.teammember')),
            ],
            options={
                'unique_together': {('team_member', 'project')},
            },
        ),
    ]
