# Generated by Django 4.2.23 on 2025-06-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0012_datacollectors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataCollectors',
            new_name='Ratings',
        ),
    ]
