# Generated by Django 4.2.23 on 2025-06-17 10:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacollectors_app', '0013_rename_datacollectors_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='ratings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='rated_by',
            field=models.CharField(blank=True, help_text='Who provided this rating', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('on-hold', 'On Hold'), ('planning', 'Planning'), ('finalised', 'Finalised')], default='planning', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='experience_level',
            field=models.CharField(choices=[('foa', 'FOA'), ('supervisor', 'Supervisor'), ('backchecker', 'Backchecker'), ('regular', 'Regular'), ('new_enumerator', 'New Enumerator')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='performance_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('data_collector', 'Data Collector')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='rotation_rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('deployed', 'Deployed'), ('inactive', 'Inactive')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='ve_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='ratings',
            index=models.Index(fields=['team_member', 'project'], name='datacollect_team_me_3f86dd_idx'),
        ),
        migrations.AddIndex(
            model_name='ratings',
            index=models.Index(fields=['rating'], name='datacollect_rating_6c4776_idx'),
        ),
        migrations.AddIndex(
            model_name='ratings',
            index=models.Index(fields=['created_at'], name='datacollect_created_9181a1_idx'),
        ),
    ]
